exports.seed = knex => knex('answers')
  .del()
  .then(() => knex('answers').insert([
    {
      user_id: 2,
      question_position: 1,
      answer: 'Vilket datum önskar du att er vigsel äger rum?',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 2,
      answer: 'Vilket datum skulle passa dig bättre?',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 3,
      answer: 'ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 4,
      answer: '10',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 5,
      answer: 'Fredrik',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 6,
      answer: 'Nobel',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 7,
      answer: 'Klintvägen 19 lgh 1201',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 8,
      answer: '90737',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 9,
      answer: 'Ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 10,
      answer: 'Umeå',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 11,
      answer: 'Sverige',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 12,
      answer: 'Ylva',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 13,
      answer: 'Jansson',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 14,
      answer: 'Åkervägen 5',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 15,
      answer: '13239',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 16,
      answer: 'Ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 17,
      answer: 'Saltsjö-boo',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 18,
      answer: 'Sverige',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 19,
      answer: '198603222392',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 20,
      answer: 'Bertil Bo',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 21,
      answer: 'Bom',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 22,
      answer: 'Tapparegatan 2',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 23,
      answer: '98137',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 24,
      answer: 'Kiruna',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      question_position: 25,
      answer: 'nej',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 1,
      answer: 'Vilket datum önskar du att er vigsel äger rum?',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 2,
      answer: 'Vilket datum skulle passa dig bättre?',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 3,
      answer: 'ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 4,
      answer: '10',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 5,
      answer: 'Fredrik',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 6,
      answer: 'Nobel',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 7,
      answer: 'Klintvägen 19 lgh 1201',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 8,
      answer: '90737',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 9,
      answer: 'Ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 10,
      answer: 'Umeå',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 11,
      answer: 'Sverige',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 12,
      answer: 'Ylva',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 13,
      answer: 'Jansson',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 14,
      answer: 'Åkervägen 5',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 15,
      answer: '13239',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 16,
      answer: 'Ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 17,
      answer: 'Saltsjö-boo',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 18,
      answer: 'Sverige',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      question_position: 19,
      answer: '198603222392',
      form_id: 1,
      question_type: 'single',
    },
  ]));
