exports.seed = knex => knex('answers')
  .del()
  .then(() => knex('answers').insert([
    {
      user_id: 2,
      answer: 'Vilket datum önskar du att er vigsel äger rum?',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Vilket datum skulle passa dig bättre?',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: '10',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Fredrik',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Nobel',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Klintvägen 19 lgh 1201',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: '90737',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Umeå',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Sverige',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Ylva',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Jansson',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Åkervägen 5',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: '13239',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Saltsjö-boo',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Sverige',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: '198603222392',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Bertil Bo',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Bom',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Tapparegatan 2',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: '98137',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'Kiruna',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 2,
      answer: 'nej',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Vilket datum önskar du att er vigsel äger rum?',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Vilket datum skulle passa dig bättre?',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: '10',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Fredrik',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Nobel',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Klintvägen 19 lgh 1201',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: '90737',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Umeå',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Sverige',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Ylva',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Jansson',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Åkervägen 5',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: '13239',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Ja',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Saltsjö-boo',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: 'Sverige',
      form_id: 1,
      question_type: 'single',
    },
    {
      user_id: 3,
      answer: '198603222392',
      form_id: 1,
      question_type: 'single',
    },
  ]));
